#:schema node_modules/wrangler/config-schema.json
name = "sg-finland-frontend"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = [ "nodejs_compat" ]

[placement]
mode = "smart"

[vars]
PUBLIC_APP_URL = "https://sg-finland-frontend.pages.dev"
PUBLIC_TWICPICS_DOMAIN = ""
AUTH_TRUST_HOST = "true"
PUBLIC_AUTH_DISCORD_ID = "1213378673458290738"
PUBLIC_DISCORD_SERVER_ID = "1163012455539163157"